"""empty message

Revision ID: d4a69a857373
Revises: 668001373a61
Create Date: 2024-11-21 04:07:05.859283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4a69a857373'
down_revision = '668001373a61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_column('pdf_path')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('study_hours', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('study_time', sa.String(length=20), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_index('ix_users_email')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('preferred_study_time')
        batch_op.drop_column('preferred_study_hours')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_study_hours', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('preferred_study_time', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_users_email', ['email'], unique=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.drop_column('study_time')
        batch_op.drop_column('study_hours')

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_path', sa.VARCHAR(length=200), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
